MAIN_VPC = "this_main_vpc"
PUB_01 = "this_pub_01"
PUB_02 = "this_pub_02"
PRI_01 = "this_pri_01"
PRI_02 = "this_pri_02"
PUB_RT = "Pub_Route_Tb1"
GTWAY = "this_gw"
PUB_RT_02 = "Pub_Route_Tb2"
PUB_RT_01 = "Pub_Route_Tb1"
PRI_RT_01 = "Pri_Route_Tb1"
PRI_RT_02 = "Pri_Route_Tb2"
NAT_GTWY = = "gw_gateway"